[platformio]
src_dir = .
description = Example of polling an encoder

[env]
framework = arduino
lib_extra_dirs = ../../
build_src_filter =
  +<**>
  +<../../src/RotaryEncoder.cpp>
build_flags = 
	-D DEBUG=0
monitor_speed = 115200

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
upload_speed = 57600

[env:uno]
platform = atmelavr
board = uno

[env:esp8266]
platform = espressif8266
board = nodemcuv2

[env:esp32]
platform = espressif32
board = esp32dev
